# Generated by Django 5.2.17 on 2026-08-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbbreviationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(db_index=True, max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('highlighted', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('for_review', 'For Review'), ('rejected', 'Rejected')], db_index=True, default='for_review', max_length=20)),
            ],
            options={
                'ordering': ['abbreviation', '-created_at'],
                'unique_together': {('abbreviation', 'description')},
            },
        ),
    ]
