# Generated by Django 5.2.17 on 2026-08-26 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abb_app', '0002_remove_abbreviationentry_highlighted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abbreviationentry',
            options={'ordering': ['abbreviation', '-created_at'], 'verbose_name': 'Abbreviation entry', 'verbose_name_plural': 'Abbreviation entries'},
        ),
    ]
