from typing import Dict, List, Optional, TypedDict, Union

from abb_app.models import AbbreviationEntry


class Abbreviation(TypedDict):
    """Universal abbreviation structure"""
    abbreviation: str
    descriptions: List[str]  # All possible descriptions
    selected_description: Optional[str]  # User selected or entered description
    count: Optional[int]  # Number of occurrences in text
    contexts: Optional[List[str]]  # Context snippets
    correct_form: Optional[str]  # For mixed-character cases
    highlighted: Optional[List[Dict]]  # For display
    status: Optional[str]  # For tracking state
    is_ai_generated: bool # is the description was generated by model?


def load_approved_dictionary() -> List[Abbreviation]:
    entries = AbbreviationEntry.objects.filter(
        status='approved'
    ).values('abbreviation', 'description')

    grouped: Dict[str, List[str]] = {}
    for entry in entries:
        grouped.setdefault(entry['abbreviation'], []).append(
            entry['description']
        )

    return [
        {
            'abbreviation': abbreviation,
            'descriptions': descriptions,
        }
        for abbreviation, descriptions in grouped.items()
    ]


def get_selected_abbreviations(
    doc_abbs: List[Abbreviation],
) -> List[Dict[str, str]]:
    return [
        {
            'abbreviation': abb['abbreviation'],
            'description': abb['selected_description'],
        }
        for abb in doc_abbs
        if abb.get('selected_description') is not None
    ]


def update_abbreviation_selection(
    doc_abbs: List[Abbreviation],
    abbreviation: str,
    description: Optional[str],
    action: str,
) -> None:
    entry = next(
        (
            item for item in doc_abbs
            if item['abbreviation'] == abbreviation
        ),
        None,
    )
    if entry is None:
        raise ValueError('Abbreviation not found')

    if action == 'skip':
        entry['selected_description'] = None
        return

    if action != 'add':
        raise ValueError('Invalid action')
    if not description:
        raise ValueError('Description is required')

    entry['selected_description'] = description
    if description in entry['descriptions']:
        return

    AbbreviationEntry.objects.get_or_create(
        abbreviation=entry.get('correct_form') or abbreviation,
        description=description,
        defaults={
            'status': 'for_review',
            'highlighted': entry.get('highlighted'),
        },
    )


def compare_abbreviations(
        old_abbs: List[Abbreviation],
        new_abbs: Union[List[Dict[str, str]], List[Abbreviation]],
    ) -> Dict[str, List[Abbreviation]]:
    """
    Compare new and old abbreviation tables.
    Returns dictionary with:
        - 'missing_abbs': abbreviations present in old but not in new
        - 'new_found': abbreviations present in new but not in old
    """
    results: Dict[str, List[Abbreviation]] = {}

    # Create sets of abbreviations for efficient comparison
    old_abb_set = {abb['abbreviation'] for abb in old_abbs}
    if new_abbs and isinstance(new_abbs[0], dict):
        if 'description' in new_abbs[0]:
            get_descriptions = lambda abb: [abb['description']]  # Wrap in list
        elif 'descriptions' in new_abbs[0]:
            get_descriptions = lambda abb: abb['descriptions']  # Use as is
        else:
            raise ValueError("Invalid format for new_abbs")

    new_abb_set = {abb['abbreviation'] for abb in new_abbs}

    # Find abbreviations that are in old but not in new
    results['missing_abbs'] = [
        abb for abb in old_abbs
        if abb['abbreviation'] not in new_abb_set
    ]
    # Wrap description in a list to match the structure of old_abbs
    results['new_found'] = [
        {
            'abbreviation': abb['abbreviation'],
            'descriptions': get_descriptions(abb)
        }
        for abb in new_abbs
        if abb['abbreviation'] not in old_abb_set
    ]

    return results
